name: technology-data
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - pip
  # for running the package
  - snakemake-minimal>=8.5
  - pandas>=2.1
  - numpy
  - beautifulsoup4
  - xlrd
  - scipy
  - openpyxl>=3.1.2
  - packaging
  - pytest=8.3.2

  - pip:
    - tabula-py
    - currencyconverter
